# Generated by Django 2.1.2 on 2020-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgsf_database', '0002_employee_termination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.TextField(max_length=200),
        ),
    ]
